# load("@io_bazel_rules_go//proto:go_proto_library.bzl", "go_proto_library")

# go_proto_library(
#     name = "build_go",
#     srcs = [
#         "build.proto"
#     ],
#     visibility = ["//visibility:public"],
# )

# go_proto_library(
#     name = "build_event_stream_go",
#     srcs = [
#         "build_event_stream.proto",
#     ],
#     visibility = ["//visibility:public"],
# )
