load("@io_bazel_rules_go//proto:go_proto_library.bzl", "go_proto_library")

go_proto_library(
    name = "build_go",
    srcs = [
        "build.proto"
    ],
    visibility = ["//visibility:public"],
)
