# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.

# Site settings These are used to personalize your new site. If you look in the
# HTML files, you will see them accessed via {{ site.title }}, {{ site.email }},
# and so on. You can create any custom variable you would like, and they will be
# accessible in the templates via {{ site.myvariable }}.
title: Bzl
logo: https://user-images.githubusercontent.com/50580/78734724-3c7fe200-7906-11ea-89b2-ddedb444f3b4.png
description: >- # this means to ignore newlines until "baseurl:"
  Bzl documentation site
baseurl: "/bzl" # the subpath of your site, e.g. /blog
url: "https://docs.bzl.io" # the base hostname & protocol for your site, e.g. http://example.com
gitweb: "https://github.com/bzl-io/bzl/blob/master"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: light
footer_content: "Copyright &copy; 2021 Stack.Build."


# Aux links for the upper right navigation
aux_links:
  "Bzl on github":
    - "https://github.com/bzl-io/bzl"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
