load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "command",
    srcs = [
        "command.go",
    ],
    deps = [
        "@com_github_urfave_cli//:go_default_library",
    ],
    importpath = "github.com/bzl-io/bzl/command",
    visibility = ["//visibility:public"],
    data = [
    ],
)
